<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="goalmodel"
    nsURI="http://www.cs.toronto.edu/km/goalmodel" nsPrefix="goalmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Contribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContributionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Goal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContributionType">
    <eLiterals name="HELP" value="1"/>
    <eLiterals name="HURT" value="-1"/>
    <eLiterals name="MAKE" value="2"/>
    <eLiterals name="BREAK" value="-2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DecompositionType">
    <eLiterals name="OR"/>
    <eLiterals name="AND" value="1"/>
    <eLiterals name="LEAF" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="#//LabelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DecompositionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Goal"
        eOpposite="#//Goal/goal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goal" upperBound="-1" eType="#//Goal"
        containment="true" resolveProxies="false" eOpposite="#//Goal/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Contribution"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LabelType">
    <eLiterals name="Satisfied" value="2"/>
    <eLiterals name="Denied" value="-2"/>
    <eLiterals name="PartiallySatisfied" value="1"/>
    <eLiterals name="PartiallyDenied" value="-1"/>
    <eLiterals name="Unknown"/>
    <eLiterals name="Conflict" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
