<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MyEditor"
    nsURI="MyEditor" nsPrefix="MyEditor">
  <eClassifiers xsi:type="ecore:EClass" name="MyCanvas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boxes" upperBound="-1"
        eType="#//Box" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Line" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Box">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Jen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceBox" lowerBound="1"
        eType="#//Box"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetBox" lowerBound="1"
        eType="#//Box"/>
  </eClassifiers>
</ecore:EPackage>
