/* Generated By:JavaCC: Do not edit this line. TelosParserConstants.java */
package edu.toronto.cs.telos;

public interface TelosParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int IN = 9;
  int ISA = 10;
  int WITH = 11;
  int END = 12;
  int INTEGER_LITERAL = 13;
  int DECIMAL_LITERAL = 14;
  int HEX_LITERAL = 15;
  int OCTAL_LITERAL = 16;
  int FLOATING_POINT_LITERAL = 17;
  int EXPONENT = 18;
  int CHARACTER_LITERAL = 19;
  int STRING_LITERAL = 20;
  int ID = 21;
  int LETTER = 22;
  int DIGIT = 23;
  int COMMA = 24;
  int COLON = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"IN\"",
    "\"ISA\"",
    "\"WITH\"",
    "\"END\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\",\"",
    "\":\"",
  };

}
